import type { Profile, Skills, Experience, Project, NavLink } from "@/types";

export const profile: Profile = {
  name: "John Paul Lagda",
  title: "Full Stack Web Developer",
  email: "japs03081995@gmail.com",
  phone: "+639524839511",
  location: "Imus, Cavite, Philippines",
  github: "https://github.com/johnpaullagda08",
  linkedin: "https://www.linkedin.com/in/john-paul-lagda-7aa0451b2/",
  summary:
    "I am a web developer with a vast array of knowledge in different front end and back end technologies, responsive frameworks, and databases. Dedicated to perfecting my craft by learning from more seasoned developers, remaining humble, and continuously making strides to learn all that I can about development.",
};

export const skills: Skills = {
  frontend: ["HTML", "CSS", "JavaScript", "Bootstrap", "Vuetify", "Vue", "jQuery", "React"],
  backend: ["Node.js", "Express.js", "PHP"],
  databases: ["MySQL", "NoSQL", "MSSQL"],
  tools: ["VS Code", "GitLab", "GitHub", "NPM", "Yarn", "REST API"],
};

export const experience: Experience[] = [
  {
    company: "HRD Singapore PTE LTD",
    location: "Singapore",
    roles: [
      {
        title: "Software and Full Stack Web Developer",
        period: "January 2017 - Present",
        responsibilities: [
          "Develop web applications for various departments",
          "Select programming languages, tools, database and platforms",
          "Maintain SQL, MySQL, NoSQL databases",
          "Maintain all department systems",
          "Train team members in Full Stack JavaScript",
        ],
      },
      {
        title: "Autocad and Architrend Encoder",
        period: "May 2013 - December 2016",
        responsibilities: [
          "House Socket Plan Encoder and Checker",
          "Multi Process of Socket plan",
          "House Wire route Plan Encoder and Checker",
        ],
      },
    ],
  },
  {
    company: "DATACOM",
    location: "Imus, Cavite",
    roles: [
      {
        title: "Computer Programmer",
        period: "June 2011 - May 2013",
        responsibilities: [],
      },
    ],
  },
];

export const projects: Project[] = [
  {
    slug: "photobooth",
    name: "Photobooth",
    description: "Professional browser-based photobooth platform for event businesses - capture, customize, print, and share photo strips instantly",
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Canvas API", "WebRTC"],
    category: "react",
    image: "/projects/photobooth-hero.png",
    images: [
      "/projects/photobooth-hero.png",
      "/projects/photobooth-features.png",
      "/projects/photobooth-how-it-works.png",
      "/projects/photobooth-camera.png",
      "/projects/photobooth-countdown.png",
      "/projects/photobooth-print-layout.png",
      "/projects/photobooth-printing.png",
      "/projects/photobooth-printer.png",
      "/projects/photobooth-launch-page.png",
    ],
    imageCaptions: [
      "Landing page with feature highlights and call-to-action",
      "Complete feature overview showing all capabilities",
      "Step-by-step workflow explanation for users",
      "Live camera interface with real-time preview",
      "Animated countdown before photo capture",
      "Print layout customization with drag-and-drop",
      "Print preview and confirmation screen",
      "Thermal printer integration and settings",
      "Event launch page with custom branding",
    ],
    url: "https://logthephotobooth-two.vercel.app/",
    role: "Solo Developer",
    year: "2024",
    duration: "3 months",
    metrics: [
      { value: "500+", label: "Photo Sessions" },
      { value: "12", label: "Events Deployed" },
      { value: "98%", label: "Uptime" },
      { value: "<2s", label: "Print Time" },
    ],
    about: "Built from the ground up for photobooth rental businesses, this application transforms any browser into a professional photo capture station. Unlike traditional photobooth software that requires expensive installations and proprietary hardware, this solution runs entirely in the browser while delivering studio-quality results. The platform handles the complete workflow from capture to print, enabling business owners to serve more clients with less technical overhead. Currently deployed at events across multiple venues, processing hundreds of photo sessions.",
    features: [
      { title: "Multi-Camera Support", description: "WebRTC integration supporting webcam, DSLR via HDMI, USB cameras, and WiFi devices", icon: "camera" },
      { title: "Smart Capture", description: "Multi-shot sequences with animated countdown overlays and audio cues", icon: "timer" },
      { title: "Live Filters", description: "10+ real-time effects including B&W, vintage, sepia, and custom LUT support", icon: "sparkles" },
      { title: "Theme Builder", description: "Drag-and-drop templates for weddings, birthdays, corporate events, and holidays", icon: "palette" },
      { title: "Print Compositor", description: "Canvas-based 2x6 and 4x6 layouts with custom borders and branding", icon: "layout" },
      { title: "Instant Print", description: "One-click thermal printer integration with auto paper detection", icon: "printer" },
      { title: "QR Sharing", description: "Instant mobile sharing - guests scan and download to their phones", icon: "qrcode" },
      { title: "Offline Ready", description: "PWA architecture ensuring reliability even with unstable venue WiFi", icon: "wifi" },
    ],
  },
  {
    slug: "homes-system",
    name: "Homes System",
    description: "Centralized admin platform managing operations across all company departments with role-based access and real-time dashboards",
    tech: ["Vue", "Vuetify", "Node.js", "Express", "MySQL", "Socket.io"],
    category: "vue",
    image: "/projects/homes-system.jpg",
    role: "Lead Developer",
    year: "2020",
    duration: "6 months",
    metrics: [
      { value: "100+", label: "Daily Users" },
      { value: "8", label: "Departments" },
      { value: "50%", label: "Time Saved" },
    ],
    about: "The Homes System serves as the central nervous system for HRD Singapore's operations, consolidating data and workflows from multiple departments into a single unified platform. Built to replace a collection of disconnected spreadsheets and legacy tools, this system now handles daily operations for 100+ employees across different teams. The architecture prioritizes real-time data synchronization and role-based access control to ensure each department sees only relevant information.",
    features: [
      { title: "Role-Based Access", description: "Granular permissions for department heads, managers, and staff", icon: "shield" },
      { title: "Live Dashboard", description: "Real-time KPIs, task progress, and performance metrics", icon: "chart" },
      { title: "Document Management", description: "Version control and approval workflows for all files", icon: "folder" },
      { title: "Task Tracking", description: "Cross-department assignment with automated notifications", icon: "tasks" },
      { title: "Audit Logging", description: "Comprehensive logging for compliance and accountability", icon: "clipboard" },
      { title: "API Integration", description: "RESTful API for external systems and mobile apps", icon: "code" },
    ],
  },
  {
    slug: "tachibana-rendering",
    name: "Tachibana Rendering System",
    description: "Automated PDF generation pipeline that transforms ICAD data into multiple output formats on demand",
    tech: ["Vue", "Vuetify", "Node.js", "Express", "MySQL", "PDFKit"],
    category: "vue",
    image: "/projects/tachibana-rendering.jpg",
    role: "Full Stack Developer",
    year: "2021",
    duration: "4 months",
    metrics: [
      { value: "1000+", label: "PDFs Generated" },
      { value: "15+", label: "Templates" },
      { value: "90%", label: "Time Reduced" },
    ],
    about: "This system automates what was previously a manual, error-prone process of generating technical PDFs from ICAD data. Engineers submit rendering requests through a simple interface, and the system queues, processes, and delivers formatted documents automatically. The pipeline handles multiple output formats and templates, significantly reducing turnaround time from hours to minutes while eliminating human transcription errors.",
    features: [
      { title: "Queue Engine", description: "Concurrent processing of multiple requests without blocking", icon: "layers" },
      { title: "Template Library", description: "15+ pre-configured PDF layouts for different documents", icon: "file" },
      { title: "Auto Extraction", description: "Data validation from ICAD system via API integration", icon: "download" },
      { title: "Batch Processing", description: "Bulk document generation with progress tracking", icon: "stack" },
      { title: "Email Delivery", description: "Automatic attachment and notification to requesters", icon: "mail" },
      { title: "Render History", description: "Searchable archive with one-click re-generation", icon: "history" },
    ],
  },
  {
    slug: "ihs-qa-system",
    name: "IHS Question and Answer System",
    description: "Internal Stack Overflow-style knowledge base where developers share solutions and document tribal knowledge",
    tech: ["Vue", "Vuetify", "Node.js", "Express", "MySQL", "Elasticsearch"],
    category: "vue",
    image: "/projects/ihs-qa.jpg",
    role: "Full Stack Developer",
    year: "2022",
    duration: "3 months",
    metrics: [
      { value: "500+", label: "Q&As Posted" },
      { value: "40%", label: "Faster Onboarding" },
      { value: "25", label: "Active Users" },
    ],
    about: "Developed to capture and preserve institutional knowledge that was being lost in chat messages and email threads. This internal Q&A platform allows developers to ask questions, share solutions, and build a searchable knowledge base. The system has become the go-to resource for onboarding new team members and solving recurring technical challenges, reducing duplicate questions and accelerating problem resolution across the development team.",
    features: [
      { title: "Full-Text Search", description: "Elasticsearch with relevance ranking and filters", icon: "search" },
      { title: "Markdown Editor", description: "Syntax highlighting for code in 20+ languages", icon: "code" },
      { title: "Voting System", description: "Upvoting and accepted answers surface best solutions", icon: "thumbsup" },
      { title: "Tag Categories", description: "Tag-based organization with subscriptions for experts", icon: "tag" },
      { title: "Smart Suggestions", description: "Related questions to reduce duplicate posts", icon: "lightbulb" },
      { title: "Reputation System", description: "Activity feed and points to encourage participation", icon: "award" },
    ],
  },
  {
    slug: "awarding-system",
    name: "Awarding System",
    description: "Certificate and award generator with customizable templates, bulk creation, and print-ready PDF output",
    tech: ["Vue", "Vuetify", "Node.js", "Express", "MySQL", "Puppeteer"],
    category: "vue",
    image: "/projects/awarding-system.jpg",
    role: "Full Stack Developer",
    year: "2021",
    duration: "2 months",
    metrics: [
      { value: "2000+", label: "Certificates" },
      { value: "95%", label: "Time Saved" },
      { value: "10", label: "Templates" },
    ],
    about: "Built to streamline the company's employee recognition program, this system transforms the tedious process of creating individual award certificates into a few clicks. HR uploads recipient data, selects templates, and the system generates professionally formatted, print-ready PDFs. What previously took days of manual work in graphic design software now completes in minutes, enabling more frequent recognition programs and boosting employee morale.",
    features: [
      { title: "Template Editor", description: "Drag-and-drop positioning for logos, text, and signatures", icon: "edit" },
      { title: "Bulk Import", description: "CSV/Excel import with data validation", icon: "upload" },
      { title: "Dynamic Fields", description: "Placeholders for name, date, award type, and custom data", icon: "variable" },
      { title: "HD Output", description: "High-resolution PDF optimized for professional printing", icon: "printer" },
      { title: "Template Library", description: "Pre-designed layouts for different award categories", icon: "layout" },
      { title: "Digital Signatures", description: "QR code verification for authenticity", icon: "shield" },
    ],
  },
  {
    slug: "mailing-monitoring",
    name: "Mailing Monitoring System",
    description: "Automated data aggregation platform that collects reports from multiple sources and delivers scheduled email summaries",
    tech: ["PHP", "JavaScript", "jQuery", "MySQL", "PHPMailer", "Cron"],
    category: "php",
    image: "/projects/mailing-monitoring.jpg",
    role: "Full Stack Developer",
    year: "2019",
    duration: "2 months",
    metrics: [
      { value: "100+", label: "Weekly Reports" },
      { value: "0", label: "Manual Hours" },
      { value: "99%", label: "Delivery Rate" },
    ],
    about: "This system eliminates the manual work of collecting data from various departments and compiling reports for management. It automatically pulls information from multiple database sources, aggregates the data according to configurable rules, and sends formatted email reports on schedule. The platform has reduced weekly reporting overhead from several hours to zero human intervention while ensuring stakeholders receive timely, accurate information.",
    features: [
      { title: "Multi-Source Data", description: "Aggregation from MySQL, MSSQL, and REST APIs", icon: "database" },
      { title: "Report Templates", description: "Configurable charts, tables, and summary statistics", icon: "chart" },
      { title: "Flexible Scheduling", description: "Cron-based triggers for daily, weekly, monthly reports", icon: "clock" },
      { title: "Distribution Lists", description: "Recipient management with conditional routing", icon: "users" },
      { title: "Delivery Tracking", description: "Open rates, bounce handling, and retry logic", icon: "check" },
      { title: "Report Archive", description: "Historical data access and trend comparisons", icon: "archive" },
    ],
  },
  {
    slug: "error-guide",
    name: "Error Guide System",
    description: "Monitoring of errors in Autocad and Architrend",
    tech: ["PHP", "JavaScript", "jQuery", "MySQL"],
    category: "php",
    image: "/projects/error-guide.jpg",
  },
  {
    slug: "denki-pattern",
    name: "Denki Pattern",
    description: "List of electrical items with specifications and auto email functionality",
    tech: ["PHP", "JavaScript", "jQuery", "MySQL"],
    category: "php",
    image: "/projects/denki-pattern.jpg",
  },
  {
    slug: "kansen-proposal",
    name: "Kansen Proposal",
    description: "Automatic data gathering with auto update and email notifications",
    tech: ["PHP", "JavaScript", "jQuery", "MySQL"],
    category: "php",
    image: "/projects/kansen-proposal.jpg",
  },
  {
    slug: "wiring-workguide",
    name: "Wiring Connection Workguide",
    description: "Process workguide for wiring connections",
    tech: ["PHP", "JavaScript", "jQuery", "MySQL"],
    category: "php",
    image: "/projects/wiring-workguide.jpg",
  },
  {
    slug: "unit-wiring-supplies",
    name: "Unit Wiring Supplies System",
    description: "Inventory management system for unit wiring supplies",
    tech: ["PHP", "JavaScript", "jQuery", "MySQL"],
    category: "php",
    image: "/projects/unit-wiring-supplies.jpg",
  },
  {
    slug: "re-email-henkou",
    name: "Re-Email Henkou System",
    description: "Email system with PDF attachment functionality",
    tech: ["PHP", "JavaScript", "jQuery", "MySQL"],
    category: "php",
    image: "/projects/re-email-henkou.jpg",
  },
  {
    slug: "survey-system",
    name: "Survey System",
    description: "Survey platform for resignation and other company activities",
    tech: ["PHP", "JavaScript", "jQuery", "MySQL"],
    category: "php",
    image: "/projects/survey-system.jpg",
  },
  {
    slug: "borrowing-system",
    name: "Borrowing System",
    description: "Monitoring and tracking of borrowed items",
    tech: ["PHP", "JavaScript", "jQuery", "MySQL"],
    category: "php",
    image: "/projects/borrowing-system.jpg",
  },
  {
    slug: "unit-wiring-message",
    name: "Unit Wiring Message",
    description: "Messaging system for all staffs or specific teams",
    tech: ["PHP", "JavaScript", "jQuery", "MySQL"],
    category: "php",
    image: "/projects/unit-wiring-message.jpg",
  },
];

export const navLinks: NavLink[] = [
  { name: "About", href: "#about" },
  { name: "Skills", href: "#skills" },
  { name: "Experience", href: "#experience" },
  { name: "Projects", href: "#projects" },
];
